### PR TITLE
Fix triangle node overdraw

### LINKED ISSUE #391: Triangle overdraw
The triangle points iterator should not return the same point twice. This test fails:

```rust
let triangle = Triangle::new(Point::new(10, 10), Point::new(30, 20), Point::new(20, 25));

let styled = triangle.into_styled(PrimitiveStyle::with_stroke(BinaryColor::On, 1));

let mut display: MockDisplay<BinaryColor> = MockDisplay::new();

// Uncomment to pass failing test
// display.set_allow_overdraw(true);

styled.draw(&mut display).unwrap();
```

Note: There is a `FIXME` in `triangle/styled.rs` that should be fixed/removed when this issue is resolved.

### PR DESCRIPTION
**Pull request by jamwaffles**
Hi! Thank you for helping out with Embedded Graphics development! Please:

- [x] Check that you've added passing tests and documentation
- [x] Add a simulator example(s) where applicable
- [x] Add a `CHANGELOG.md` entry in the **Unreleased** section under the appropriate heading (**Added**, **Fixed**, etc) and appropriate crate (`embedded-graphics`, `simulator`, `tinytga`, `tinybmp`) if your changes affect the **public API**
- [x] Run `rustfmt` on the project
- [x] Run `./build.sh` (Linux/macOS only) and make sure it passes. If you use Windows, check that CI passes once you've opened the PR.

## PR description

Each node of a triangle was drawn twice. This PR fixes that and closes #391 in the process. The triangle algorithm is kind of gnarly, so the fix is too...

### CODE REVIEW

File: embedded-graphics/src/primitives/triangle/styled.rs [hunk 1]
```diff
@@ -229,7 +229,6 @@ mod tests {
         let styled = triangle.into_styled(PrimitiveStyle::with_stroke(BinaryColor::On, 1));
 
         let mut tri_display: MockDisplay<BinaryColor> = MockDisplay::new();
-        // FIXME: Triangles should not be overdrawing
         tri_display.set_allow_overdraw(true);
```
Comment (rfuest) [inline embedded-graphics/src/primitives/triangle/styled.rs:232]: Is `set_allow_overdraw` still required for this test?

File: embedded-graphics/src/primitives/triangle/scanline_iterator.rs [hunk 2]
```diff
@@ -106,13 +106,13 @@ impl ScanlineIterator {
...
-                        } else {
-                            let (l, r) = sort_two_yx(n_ac, n_b);
-                            IterState::LeftRight(l, r)
+                        match n_ac.y.cmp(&n_b.y) {
+                            Ordering::Less => self.update_ac(),
+                            Ordering::Greater => self.update_b(),
+                            Ordering::Equal => {
+                                let (l, r) = sort_two_yx(n_ac, n_b);
+                                IterState::LeftRight(l, r)
+                            }
```
Comment (rfuest) [inline embedded-graphics/src/primitives/triangle/scanline_iterator.rs:115]: Nice, I always forget about matching on `cmp`.

File: embedded-graphics/src/primitives/triangle/styled.rs (hunk 1 above)
Comment (jamwaffles) [reply embedded-graphics/src/primitives/triangle/styled.rs]: Oh jeez... I deleted the comment but not the line :facepalm:
